<h1>hello comment form</h1>
<form action="" method="post" class="comment_form"  >
    <input type="text" name='comment' placeholder='Add Comment' >
    <br>
    <input type="submit" class="submit" name='submit' value='Submit'>
</form>
<?php //$form_url = $block->getFormAction() ?>

<!--<script type = "text/x-magento-init">-->
<!--    {-->
<!--        "*" : {-->
<!--                "OpenTechiz/js/commentajax";{-->
<!--                    "AjaxCommentPostUrl": "--><?php //echo $form_url; ?><!--"-->
<!--                    }-->
<!--              }-->
<!--    }-->
<!--</script>-->
