<h1>hello comment form</h1>
<form action="" method="post" class="comment_form"  >
    <input type="type" name="blog_id" value="<?php echo $block->getPostId();?>">
    <input type="type" name="customer_id" value="<?php echo $block->getCustomerId();?>">
<!--    <input type="type" name="test" value="--><?php //echo $block->isLoggedIn();?><!--">-->
    <input type="text" name='comment' required placeholder='Add Comment' >
    <br>
    <input type="submit" class="submit" name='submit' value='Submit'>
</form>
<div class="note"></div>
<?php $form_url = $block->getFormAction() ?>

<script type = "text/x-magento-init">
    {
        "*" : {
                "OpenTechiz/js/commentajax";{
                    "AjaxCommentPostUrl": "<?php echo $form_url; ?>"
                    }
              }
    }
</script>
